In [94]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from pandas_profiling import ProfileReport
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_validate
from sklearn import tree
from sklearn.feature_selection import RFE
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [95]:
data =  pd.read_csv('data/letter-recognition.data', sep=",", header = None)
data

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0      T   2   8   3   5   1   8  13   0   6   6  10   8   0   8   0   8
1      I   5  12   3   7   2  10   5   5   4  13   3   9   2   8   4  10
2      D   4  11   6   8   6  10   6   2   6  10   3   7   3   7   3   9
3      N   7  11   6   6   3   5   9   4   6   4   4  10   6  10   2   8
4      G   2   1   3   1   1   8   6   6   6   6   5   9   1   7   5  10
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
19995  D   2   2   3   3   2   7   7   7   6   6   6   4   2   8   3   7
19996  C   7  10   8   8   4   4   8   6   9  12   9  13   2   9   3   7
19997  T   6   9   6   7   5   6  11   3   7  11   9   5   2  12   2   4
19998  S   2   3   4   2   1   8   7   2   6  10   6   8   1   9   5   8
19999  A   4   9   6   6   2   9   5   3   1   8   1   8   2   7   2   8

[20000 rows x 17 columns]

In [96]:
columnNames = ["lettr", "x_box", "y_box", "width", "thigh", "onpix", "x_bar", "y_bar", "x2_bar", "y2_bar", "xy_bar", "x2y_br", "xy2br", "x_ege", "xegvy", "y_ege", "yegvx"]

In [97]:
data.columns = columnNames

In [98]:
HandK = data[(data['lettr'] == 'H') | (data['lettr'] == 'K')]
HandK

lettr  x_box  y_box  width  thigh  onpix  x_bar  y_bar  x2_bar  y2_bar  \
21        H      4      5      5      4      4      7      7       6       6   
28        H      6      9      8      7      6      8      6       6       7   
64        H      3      3      4      1      2      8      7       5       6   
66        H      3      5      5      4      3      7      8       3       6   
69        H      8     12      8      6      4      9      8       4       5   
...     ...    ...    ...    ...    ...    ...    ...    ...     ...     ...   
19921     K      7     14      8      8      5      9      6       3       5   
19931     K      3      1      5      3      3      6      7       4       8   
19937     H      3      8      5      6      4      8      8       7       7   
19957     H      5      7      8      5      5      9      7       3       6   
19978     K      5     11      5      8      5      3      8       7       3   

       xy_bar  x2y_br  xy2br  x_ege  xegvy  y_ege  yegvx  
21          7       6      8      3      8      3      8  
28          7       7      9      6      8      4      8  
64          7       6      8      5      8      3      7  
66         10       6      8      3      8      3      8  
69          8       4      5      6      9      5      9  
...       ...     ...    ...    ...    ...    ...    ...  
19921      11       3      7      5      7      4      8  
19931       7       6     11      3      8      5      9  
19937       7       5      7      3      8      3      7  
19957      10       4      7      5      8      4      9  
19978       6       4     11      3      8      2     11  

[1473 rows x 17 columns]

In [99]:
MandY = data[(data['lettr'] == 'M') | (data['lettr'] == 'Y')]
MandY

lettr  x_box  y_box  width  thigh  onpix  x_bar  y_bar  x2_bar  y2_bar  \
9         M     11     15     13      9      7     13      2       6       2   
13        M      6      9      8      6      9      7      8       6       5   
26        M      7     11     11      8      9      3      8       4       5   
34        M      6      9      9      7      6      5      6       3       5   
50        Y      7     11      9      8      8      9      5       6       4   
...     ...    ...    ...    ...    ...    ...    ...    ...     ...     ...   
19940     Y      6      9      5      5      2      5      9       3       3   
19949     M      5      8      7      6      7      8      6       6       5   
19979     M      6      9     10      7     12      7      5       3       2   
19982     Y      3      9      5      6      3      7      9       1       6   
19985     M      5      6      8      4      5      9      6       2       4   

       xy_bar  x2y_br  xy2br  x_ege  xegvy  y_ege  yegvx  
9          12       1      9      8      1      1      8  
13          7       5      8      8      9      8      6  
26         10      11     10     10      9      5      7  
34         10       9      9      8      5      2      7  
50          7       8      8      3      9      8      3  
...       ...     ...    ...    ...    ...    ...    ...  
19940      10       9      5      3     10      3      4  
19949       7       7     10     11      6      2      9  
19979       7       5      8     15      7      4      6  
19982       6      11      8      2     11      2      7  
19985       9       5      7      8      6      2      8  

[1578 rows x 17 columns]

In [147]:
EandT = data[(data['lettr'] == 'E') | (data['lettr'] == 'T')]
EandT

lettr  x_box  y_box  width  thigh  onpix  x_bar  y_bar  x2_bar  y2_bar  \
0         T      2      8      3      5      1      8     13       0       6   
18        T      6     11      6      8      5      6     11       5       6   
39        E      3      4      3      6      2      3      8       6      10   
41        E      3      7      4      5      4      7      7       5       8   
62        E      6      9      4      4      2      7      7       4       7   
...     ...    ...    ...    ...    ...    ...    ...    ...     ...     ...   
19973     T      4      4      5      3      2      5     12       2       8   
19975     E      1      0      1      0      0      5      8       5       7   
19992     E      4      9      5      6      3      5      9       2      10   
19994     T      5      8      7      7      7      7      9       4       8   
19997     T      6      9      6      7      5      6     11       3       7   

       xy_bar  x2y_br  xy2br  x_ege  xegvy  y_ege  yegvx  
0           6      10      8      0      8      0      8  
18         11       9      4      3     12      2      4  
39          7       6     15      0      8      7      8  
41          8       8      9      3      9      6      9  
62         10       6     10      1      9      7      9  
...       ...     ...    ...    ...    ...    ...    ...  
19973      11       9      4      0     10      2      4  
19975       7       6     12      0      8      6     10  
19992      10       8      9      2      8      5      5  
19994       7       7      8      3     10      8      6  
19997      11       9      5      2     12      2      4  

[1564 rows x 17 columns]

In [148]:
yDataHandK = HandK.lettr
yDataMandY = MandY.lettr
yDataEandT = EandT.lettr
XDataHandK = HandK.drop(["lettr"], axis=1)
XDataMandY = MandY.drop(["lettr"], axis=1)
XDataEandT = EandT.drop(["lettr"], axis=1)

In [149]:
X_train_MandY, X_test_MandY, y_train_MandY, y_test_MandY = train_test_split(XDataMandY, yDataMandY, test_size=0.1, random_state=42)
X_train_HandK, X_test_HandK, y_train_HandK, y_test_HandK = train_test_split(XDataHandK, yDataHandK, test_size=0.1, random_state=42)
X_train_EandT, X_test_EandT, y_train_EandT, y_test_EandT = train_test_split(XDataEandT, yDataEandT, test_size=0.1, random_state=42)

In [102]:
# profile = ProfileReport(data, title="Pandas Profiling Report")
# profile

## M and Y

#### Random Forest Classifier

In [206]:
randomForest = RandomForestClassifier(max_depth=2, random_state=0)
cv_results = cross_validate(randomForest, X_train_MandY, y_train_MandY, cv=5)
print(np.mean(cv_results.get("test_score")))

0.9788732394366196


In [207]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    randomForest = RandomForestClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(randomForest, X_train_MandY, y_train_MandY, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.9570422535211268
0.9788732394366196
0.9880281690140844
0.9943661971830986
0.9964788732394366
0.9971830985915492
0.9971830985915492
0.9971830985915492
Best performance:  0.9971830985915492
Ideal max depth:  10


In [208]:
# make the best model and test with testing data
randomForest = RandomForestClassifier(max_depth=10, random_state=0)
randomForest.fit(X_train_MandY, y_train_MandY)
y_pred = randomForest.predict(X_test_MandY)
accuracy_score(y_test_MandY, y_pred)

0.9936708860759493

Let's dive deeper into the performance of our model with a confusion matrix.

In [209]:
confusion_matrix(y_test_MandY, y_pred)

array([[82,  0],
       [ 1, 75]], dtype=int64)

#### Decision Tree Classifier

In [107]:
decisionTree = tree.DecisionTreeClassifier()
cv_results = cross_validate(decisionTree, X_train_MandY, y_train_MandY, cv=5)
print(np.mean(cv_results.get("test_score")))

0.9901408450704224


In [109]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    decisionTree = tree.DecisionTreeClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(decisionTree, X_train_MandY, y_train_MandY, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.95
0.9711267605633804
0.980281690140845
0.9894366197183098
0.9922535211267605
0.9908450704225352
0.9908450704225352
0.9908450704225352
Best performance:  0.9922535211267605
Ideal max depth:  7


In [210]:
decisionTree = tree.DecisionTreeClassifier(max_depth=7, random_state=0)
decisionTree.fit(X_train_MandY, y_train_MandY)
y_pred = decisionTree.predict(X_test_MandY)
accuracy_score(y_test_MandY, y_pred)

0.9936708860759493

Let's dive deeper into the performance of our model with a confusion matrix.

In [110]:
confusion_matrix(y_test_MandY, y_pred)

array([[82,  0],
       [ 2, 74]], dtype=int64)

#### KNN

In [111]:
# Create the k-NN classifier with k=3
knn = KNeighborsClassifier(n_neighbors=5)

# Fit the classifier to the training data
knn.fit(X_train_MandY, y_train_MandY)

# Predict the classes of the test set
y_pred = knn.predict(X_test_MandY)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test_MandY, y_pred)

# Print the accuracy of the model
print("Accuracy:", accuracy)

print()
print("Cross-validation Average Test Score:")

# Perform 10-fold cross-validation
cv_results = cross_validate(knn, X_train_MandY, y_train_MandY, cv=10)
print(np.mean(cv_results.get("test_score")))

Accuracy: 0.9936708860759493

Cross-validation Average Test Score:
0.9985915492957746


In [112]:
# Tuning k Hyperparameter
max_k = 15
scores = []
for k in range(1, max_k):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_MandY, y_train_MandY)
    y_pred = knn.predict(X_test_MandY)
    cv_results = cross_validate(knn, X_train_MandY, y_train_MandY, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal k: ", scores.index(max(scores))+1)

Best performance:  0.9992957746478872
Ideal k:  1


In [211]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train_MandY, y_train_MandY)
y_pred = knn.predict(X_test_MandY)
accuracy_score(y_test_MandY, y_pred)

1.0

Let's dive deeper into the performance of our model with a confusion matrix.

In [212]:
confusion_matrix(y_test_MandY, y_pred)

array([[82,  0],
       [ 0, 76]], dtype=int64)

#### SVM

In [114]:
# Create the SVM classifier
svm = SVC(kernel='linear', C=1)

# Fit the classifier to the training data
svm.fit(X_train_MandY, y_train_MandY)

# Predict the classes of the test set
y_pred = svm.predict(X_test_MandY)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test_MandY, y_pred)

# Print the accuracy of the model
print("Accuracy:", accuracy)

print()
print("Cross-validation Average Test Score:")

# Perform 10-fold cross-validation
cv_results = cross_validate(svm, X_train_MandY, y_train_MandY, cv=10)
print(np.mean(cv_results.get("test_score")))

Accuracy: 1.0

Cross-validation Average Test Score:
0.9971830985915492


In [115]:
# Tuning C Hyperparameter
max_C = 15
scores = []
for C in range(1, max_C):
    svm = SVC(kernel='linear', C=C)
    svm.fit(X_train_MandY, y_train_MandY)
    y_pred = svm.predict(X_test_MandY)
    cv_results = cross_validate(svm, X_train_MandY, y_train_MandY, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal C: ", scores.index(max(scores))+1)

Best performance:  0.9971830985915492
Ideal C:  1


In [213]:
svm = SVC(kernel='linear', C=1)
svm.fit(X_train_MandY, y_train_MandY)
y_pred = svm.predict(X_test_MandY)
accuracy_score(y_test_MandY, y_pred)

1.0

Let's dive deeper into the performance of our model with a confusion matrix.

In [214]:
confusion_matrix(y_test_MandY, y_pred)

array([[82,  0],
       [ 0, 76]], dtype=int64)

## H and K

#### Random Forest Classifier

In [117]:
randomForest = RandomForestClassifier(max_depth=2, random_state=0)
cv_results = cross_validate(randomForest, X_train_HandK, y_train_HandK, cv=5)
cv_results

{'fit_time': array([0.12717438, 0.11025476, 0.11034441, 0.11127448, 0.10530758]),
 'score_time': array([0.00897765, 0.01052523, 0.00896811, 0.00998306, 0.00901985]),
 'test_score': array([0.84150943, 0.90943396, 0.86037736, 0.85283019, 0.8       ])}

In [119]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    randomForest = RandomForestClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(randomForest, X_train_HandK, y_train_HandK, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.8226415094339623
0.8528301886792453
0.8747169811320754
0.9162264150943397
0.9486792452830188
0.9630188679245283
0.9615094339622641
0.9622641509433961
Best performance:  0.9630188679245283
Ideal max depth:  10


In [215]:
randomForest = RandomForestClassifier(max_depth=10, random_state=0)
randomForest.fit(X_train_HandK, y_train_HandK)
y_pred = randomForest.predict(X_test_HandK)
accuracy_score(y_test_HandK, y_pred)

1.0

Let's dive deeper into the performance of our model with a confusion matrix.

In [216]:
confusion_matrix(y_test_HandK, y_pred)

array([[68,  0],
       [ 0, 80]], dtype=int64)

#### Decision Tree Classifier

In [121]:
decisionTree = tree.DecisionTreeClassifier()
cv_results = cross_validate(decisionTree, X_train_HandK, y_train_HandK, cv=5)
print(np.mean(cv_results.get("test_score")))

0.9403773584905661


In [217]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15, 17, 20]
scores = []
for i in range(len(max_depths)):
    decisionTree = tree.DecisionTreeClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(decisionTree, X_train_HandK, y_train_HandK, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.8226415094339623
0.8475471698113208
0.8596226415094339
0.898867924528302
0.9192452830188678
0.9328301886792453
0.929811320754717
0.9350943396226417
0.9350943396226417
0.9350943396226417
Best performance:  0.9350943396226417
Ideal max depth:  15


In [218]:
decisionTree = tree.DecisionTreeClassifier(max_depth=15, random_state=0)
decisionTree.fit(X_train_HandK, y_train_HandK)
y_pred = decisionTree.predict(X_test_HandK)
accuracy_score(y_test_HandK, y_pred)

1.0

Let's dive deeper into the performance of our model with a confusion matrix.

In [219]:
confusion_matrix(y_test_HandK, y_pred)

array([[68,  0],
       [ 0, 80]], dtype=int64)

#### KNN

In [125]:
# Create the k-NN classifier with k=3
knn = KNeighborsClassifier(n_neighbors=3)

# Fit the classifier to the training data
knn.fit(X_train_HandK, y_train_HandK)

# Predict the classes of the test set
y_pred = knn.predict(X_test_HandK)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test_HandK, y_pred)

# Print the accuracy of the model
print("Accuracy:", accuracy)

print()
print("Cross-validation Average Test Score:")

# Perform 10-fold cross-validation
cv_results = cross_validate(knn, X_train_HandK, y_train_HandK, cv=10)
print(np.mean(cv_results.get("test_score")))

Accuracy: 0.9797297297297297

Cross-validation Average Test Score:
0.9546992481203007


In [126]:
# Tuning k Hyperparameter
max_k = 15
scores = []
for k in range(1, max_k):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_HandK, y_train_HandK)
    y_pred = knn.predict(X_test_HandK)
    cv_results = cross_validate(knn, X_train_HandK, y_train_HandK, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal k: ", scores.index(max(scores))+1)

Best performance:  0.9554625199362041
Ideal k:  1


In [220]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train_HandK, y_train_HandK)
y_pred = knn.predict(X_test_HandK)
accuracy_score(y_test_HandK, y_pred)

0.9864864864864865

Let's dive deeper into the performance of our model with a confusion matrix.

In [221]:
confusion_matrix(y_test_HandK, y_pred)

array([[67,  1],
       [ 1, 79]], dtype=int64)

#### SVM

In [128]:
# Create the SVM classifier
svm = SVC(kernel='linear', C=1)

# Fit the classifier to the training data
svm.fit(X_train_HandK, y_train_HandK)

# Predict the classes of the test set
y_pred = svm.predict(X_test_HandK)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test_HandK, y_pred)

# Print the accuracy of the model
print("Accuracy:", accuracy)

print()
print("Cross-validation Average Test Score:")

# Perform 10-fold cross-validation
cv_results = cross_validate(svm, X_train_HandK, y_train_HandK, cv=10)
print(np.mean(cv_results.get("test_score")))

Accuracy: 0.9662162162162162

Cross-validation Average Test Score:
0.9207507404875827


In [129]:
# Tuning C Hyperparameter
max_C = 15
scores = []
for C in range(1, max_C):
    svm = SVC(kernel='linear', C=C)
    svm.fit(X_train_HandK, y_train_HandK)
    y_pred = svm.predict(X_test_HandK)
    cv_results = cross_validate(svm, X_train_HandK, y_train_HandK, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal C: ", scores.index(max(scores))+1)

Best performance:  0.9215083162451585
Ideal C:  3


In [222]:
svm = SVC(kernel='linear', C=3)
svm.fit(X_train_HandK, y_train_HandK)
y_pred = svm.predict(X_test_HandK)
accuracy_score(y_test_HandK, y_pred)

0.9662162162162162

Let's dive deeper into the performance of our model with a confusion matrix.

In [130]:
confusion_matrix(y_test_HandK, y_pred)

array([[66,  2],
       [ 3, 77]], dtype=int64)

### E and T

#### Random Forest Classifier

In [150]:
randomForest = RandomForestClassifier(max_depth=2, random_state=0)
cv_results = cross_validate(randomForest, X_train_EandT, y_train_EandT, cv=5)
print(np.mean(cv_results.get("test_score")))

0.919696625526867


In [152]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    randomForest = RandomForestClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(randomForest, X_train_EandT, y_train_EandT, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.9047727215365589
0.919696625526867
0.9310643345700512
0.9680220085308295
0.9914742182176118
0.9936044017061659
0.994313621564322
0.994313621564322
Best performance:  0.994313621564322
Ideal max depth:  13


In [223]:
randomForest = RandomForestClassifier(max_depth=13, random_state=0)
randomForest.fit(X_train_EandT, y_train_EandT)
y_pred = randomForest.predict(X_test_EandT)
accuracy_score(y_test_EandT, y_pred)

1.0

Let's dive deeper into the performance of our model with a confusion matrix.

In [154]:
confusion_matrix(y_test_EandT, y_pred)

array([[79,  0],
       [18, 60]], dtype=int64)

#### Decision Tree Classifier

In [155]:
decisionTree = tree.DecisionTreeClassifier()
cv_results = cross_validate(decisionTree, X_train_EandT, y_train_EandT, cv=5)
print(np.mean(cv_results.get("test_score")))

0.9758335226268899


In [157]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    decisionTree = tree.DecisionTreeClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(decisionTree, X_train_EandT, y_train_EandT, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.8983720754145528
0.913293455490775
0.9239519446758031
0.9687312283889856
0.9800989374321698
0.9758335226268897
0.9772570101713738
0.9772570101713738
Best performance:  0.9800989374321698
Ideal max depth:  7


In [224]:
decisionTree = tree.DecisionTreeClassifier(max_depth=7, random_state=0)
decisionTree.fit(X_train_EandT, y_train_EandT)
y_pred = decisionTree.predict(X_test_EandT)
accuracy_score(y_test_EandT, y_pred)

0.9745222929936306

Let's dive deeper into the performance of our model with a confusion matrix.

In [225]:
confusion_matrix(y_test_EandT, y_pred)

array([[77,  2],
       [ 2, 76]], dtype=int64)

#### KNN

In [160]:
# Create the k-NN classifier with k=3
knn = KNeighborsClassifier(n_neighbors=5)

# Fit the classifier to the training data
knn.fit(X_train_EandT, y_train_EandT)

# Predict the classes of the test set
y_pred = knn.predict(X_test_EandT)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test_EandT, y_pred)

# Print the accuracy of the model
print("Accuracy:", accuracy)

print()
print("Cross-validation Average Test Score:")

# Perform 10-fold cross-validation
cv_results = cross_validate(knn, X_train_EandT, y_train_EandT, cv=10)
print(np.mean(cv_results.get("test_score")))

Accuracy: 1.0

Cross-validation Average Test Score:
0.9978622087132727


In [161]:
# Tuning k Hyperparameter
max_k = 15
scores = []
for k in range(1, max_k):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_EandT, y_train_EandT)
    y_pred = knn.predict(X_test_EandT)
    cv_results = cross_validate(knn, X_train_EandT, y_train_EandT, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal k: ", scores.index(max(scores))+1)

Best performance:  1.0
Ideal k:  2


In [226]:
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train_EandT, y_train_EandT)
y_pred = knn.predict(X_test_EandT)
accuracy_score(y_test_EandT, y_pred)

1.0

Let's dive deeper into the performance of our model with a confusion matrix.

In [227]:
confusion_matrix(y_test_EandT, y_pred)

array([[79,  0],
       [ 0, 78]], dtype=int64)

#### SVM

In [164]:
# Create the SVM classifier
svm = SVC(kernel='linear', C=1)

# Fit the classifier to the training data
svm.fit(X_train_EandT, y_train_EandT)

# Predict the classes of the test set
y_pred = svm.predict(X_test_EandT)

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test_EandT, y_pred)

# Print the accuracy of the model
print("Accuracy:", accuracy)

print()
print("Cross-validation Average Test Score:")

# Perform 10-fold cross-validation
cv_results = cross_validate(svm, X_train_EandT, y_train_EandT, cv=10)
print(np.mean(cv_results.get("test_score")))

Accuracy: 0.9681528662420382

Cross-validation Average Test Score:
0.9665957446808511


In [165]:
# Tuning C Hyperparameter
max_C = 15
scores = []
for C in range(1, max_C):
    svm = SVC(kernel='linear', C=C)
    svm.fit(X_train_EandT, y_train_EandT)
    y_pred = svm.predict(X_test_EandT)
    cv_results = cross_validate(svm, X_train_EandT, y_train_EandT, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal C: ", scores.index(max(scores))+1)

Best performance:  0.9680141843971631
Ideal C:  4


In [228]:
svm = SVC(kernel='linear', C=4)
svm.fit(X_train_EandT, y_train_EandT)
y_pred = svm.predict(X_test_EandT)
accuracy_score(y_test_EandT, y_pred)

0.9617834394904459

Let's dive deeper into the performance of our model with a confusion matrix.

In [229]:
confusion_matrix(y_test_EandT, y_pred)

array([[78,  1],
       [ 5, 73]], dtype=int64)

# Feature Selection

## Feature Selection for H and K

#### RFE for Random Forest

In [231]:
estimator = RandomForestClassifier(max_depth=2, random_state=0)
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_HandK, y_train_HandK)

In [232]:
selector.support_

array([False, False, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False,  True])

In [233]:
selected = X_train_HandK.loc[:, selector.support_]
selected

x_bar  x2_bar  xy2br  yegvx
1224       5       7     10     11
1256       6       3      9      7
3956      11       4      6     10
13842      4       6     11     10
2113       4       3     11      5
...      ...     ...    ...    ...
15164      7       1      9      7
17523      9       1      8      9
11385      6       3      8      7
19772      7      15      8      8
15091      8       6      7      7

[1325 rows x 4 columns]

In [234]:
randomForest = RandomForestClassifier(max_depth=2, random_state=0)
cv_results = cross_validate(randomForest, selected, y_train_HandK, cv=5)
cv_results

{'fit_time': array([0.29989767, 0.28907967, 0.31734705, 0.31876945, 0.31773114]),
 'score_time': array([0.02350664, 0.03144741, 0.02862263, 0.03135562, 0.02909064]),
 'test_score': array([0.84528302, 0.91698113, 0.86792453, 0.86037736, 0.81509434])}

In [235]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    randomForest = RandomForestClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(randomForest, selected, y_train_HandK, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.8166037735849058
0.8611320754716981
0.8837735849056605
0.9026415094339623
0.9109433962264151
0.9033962264150943
0.9041509433962265
0.9049056603773586
Best performance:  0.9109433962264151
Ideal max depth:  7


In [236]:
randomForest = RandomForestClassifier(max_depth=7, random_state=0)
randomForest.fit(selected, y_train_HandK)
test_selected = X_test_HandK.loc[:, selector.support_]
y_pred = randomForest.predict(test_selected)
accuracy_score(y_test_HandK, y_pred)

0.9391891891891891

#### RFE for Decision Tree

In [137]:
estimator = tree.DecisionTreeClassifier()
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_HandK, y_train_HandK)

In [138]:
selector.support_

array([False, False, False, False, False, False, False,  True, False,
        True, False,  True,  True, False, False, False])

In [139]:
selected = X_train_HandK.loc[:, selector.support_]
selected

x2_bar  xy_bar  xy2br  x_ege
1224        7       7     10      3
1256        3      10      9      3
3956        4      11      6      5
13842       6       7     11      3
2113        3      11     11      4
...       ...     ...    ...    ...
15164       1      10      9      5
17523       1      10      8      6
11385       3      10      8      4
19772      15       7      8      3
15091       6       7      7      3

[1325 rows x 4 columns]

In [140]:
decisionTree = tree.DecisionTreeClassifier()
cv_results = cross_validate(decisionTree, selected, y_train_HandK, cv=5, return_train_score=True)
cv_results

{'fit_time': array([0.00449777, 0.00301075, 0.00200534, 0.00199103, 0.00198698]),
 'score_time': array([0.0010066 , 0.00199413, 0.00099993, 0.00099707, 0.00100183]),
 'test_score': array([0.90566038, 0.95471698, 0.93584906, 0.9245283 , 0.93584906]),
 'train_score': array([0.97641509, 0.96792453, 0.96981132, 0.97264151, 0.96792453])}

In [142]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    decisionTree = tree.DecisionTreeClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(decisionTree, selected, y_train_HandK, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.8226415094339623
0.8475471698113208
0.8649056603773586
0.8898113207547171
0.9230188679245284
0.9313207547169812
0.9328301886792453
0.9320754716981131
Best performance:  0.9328301886792453
Ideal max depth:  13


In [237]:
decisionTree = tree.DecisionTreeClassifier(max_depth=13, random_state=0)
decisionTree.fit(selected, y_train_HandK)
test_selected = X_test_HandK.loc[:, selector.support_]
y_pred = decisionTree.predict(test_selected)
accuracy_score(y_test_HandK, y_pred)

0.9391891891891891

#### Scoring Methods for KNN

In [239]:
# Perform Univariate Feature Selection
selector = SelectKBest(chi2, k=2)
X_train_HandK_selected = selector.fit_transform(X_train_HandK, y_train_HandK)
X_test_HandK_selected = selector.fit_transform(X_test_HandK, y_test_HandK)

# Tuning k Hyperparameter
max_k = 15
scores = []
for k in range(1, max_k):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_HandK_selected, y_train_HandK)
    y_pred = knn.predict(X_test_HandK_selected)
    cv_results = cross_validate(knn, X_train_HandK_selected, y_train_HandK, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal k: ", scores.index(max(scores))+1)


Best performance:  0.869377990430622
Ideal k:  13


In [240]:
knn = KNeighborsClassifier(n_neighbors=13)
knn.fit(X_train_HandK_selected, y_train_HandK)
y_pred = knn.predict(X_test_HandK_selected)
accuracy_score(y_test_HandK, y_pred)

0.5608108108108109

#### RFE for SVM

In [241]:
estimator = SVC(kernel='linear', C=1)
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_HandK, y_train_HandK)

In [247]:
X_train_HandK_selected = X_train_HandK.loc[:, selector.support_]
X_test_HandK_selected = X_test_HandK.loc[:, selector.support_]

In [248]:
# Tuning C Hyperparameter with selected features
max_C = 15
scores = []
for C in range(1, max_C):
    svm = SVC(kernel='linear', C=C)
    svm.fit(X_train_HandK_selected, y_train_HandK)
    y_pred = svm.predict(X_train_HandK_selected)
    cv_results = cross_validate(svm, X_train_HandK_selected, y_train_HandK, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal C: ", scores.index(max(scores))+1)

Best performance:  0.9094098883572569
Ideal C:  7


In [249]:
svm = SVC(kernel='linear', C=7)
svm.fit(X_train_HandK_selected, y_train_HandK)
y_pred = svm.predict(X_test_HandK_selected)
accuracy_score(y_test_HandK, y_pred)

0.9527027027027027

## Feature selection for M and Y

#### RFE for Random Forest

In [251]:
estimator = RandomForestClassifier(max_depth=2, random_state=0)
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_MandY, y_train_MandY)

In [252]:
selector.support_

array([False, False, False, False, False, False,  True, False, False,
       False,  True, False,  True,  True, False, False])

In [253]:
selected = X_train_MandY.loc[:, selector.support_]
selected

y_bar  x2y_br  x_ege  xegvy
2045      10      11      1     11
2468      11      12      1     11
17140      5       8      8      6
5281      11      10      1     11
7930       7       9      9      6
...      ...     ...    ...    ...
13995     10       9      1     11
16058      9       9      1     11
10479      9      12      1     10
18334      8       6      4     10
13930      6       9      7      5

[1420 rows x 4 columns]

In [170]:
randomForest = RandomForestClassifier(max_depth=2, random_state=0)
cv_results = cross_validate(randomForest, selected, y_train_MandY, cv=5)
cv_results

{'fit_time': array([0.12686515, 0.10931301, 0.12620401, 0.12672281, 0.13226676]),
 'score_time': array([0.01096773, 0.009974  , 0.01200891, 0.00997281, 0.01300192]),
 'test_score': array([0.97887324, 0.98591549, 0.98943662, 0.98239437, 0.98239437])}

In [254]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    randomForest = RandomForestClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(randomForest, selected, y_train_MandY, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.9669014084507044
0.9838028169014084
0.9816901408450704
0.9887323943661972
0.9894366197183098
0.9915492957746478
0.9915492957746478
0.9915492957746478
Best performance:  0.9915492957746478
Ideal max depth:  10


In [255]:
randomForest = RandomForestClassifier(max_depth=10, random_state=0)
randomForest.fit(selected, y_train_MandY)
test_selected = X_test_MandY.loc[:, selector.support_]
y_pred = randomForest.predict(test_selected)
accuracy_score(y_test_MandY, y_pred)

0.9936708860759493

#### RFE for Decision Tree

In [256]:
estimator = tree.DecisionTreeClassifier()
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_MandY, y_train_MandY)

In [257]:
selector.support_

array([False,  True, False,  True, False, False, False, False, False,
       False, False, False,  True,  True, False, False])

In [258]:
selected = X_train_MandY.loc[:, selector.support_]
selected

y_box  thigh  x_ege  xegvy
2045       5      4      1     11
2468       6      8      1     11
17140      9      6      8      6
5281       4      3      1     11
7930       4      6      9      6
...      ...    ...    ...    ...
13995      3      2      1     11
16058      8      6      1     11
10479      1      1      1     10
18334     11      6      4     10
13930      1      2      7      5

[1420 rows x 4 columns]

In [259]:
decisionTree = tree.DecisionTreeClassifier()
cv_results = cross_validate(decisionTree, selected, y_train_MandY, cv=5, return_train_score=True)
cv_results

{'fit_time': array([0.00798845, 0.00499487, 0.00468731, 0.00560808, 0.00642776]),
 'score_time': array([0.00360084, 0.00200438, 0.00199485, 0.00202155, 0.00343847]),
 'test_score': array([0.98239437, 0.98239437, 0.98943662, 0.99647887, 0.98591549]),
 'train_score': array([0.99735915, 0.99823944, 0.99735915, 0.99647887, 0.99823944])}

In [180]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    decisionTree = tree.DecisionTreeClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(decisionTree, selected, y_train_MandY, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.95
0.9774647887323944
0.9774647887323944
0.9873239436619718
0.9866197183098592
0.9852112676056338
0.9852112676056338
0.9852112676056338
Best performance:  0.9873239436619718
Ideal max depth:  5


In [260]:
decisionTree = tree.DecisionTreeClassifier(max_depth=5, random_state=0)
decisionTree.fit(selected, y_train_MandY)
test_selected = X_test_MandY.loc[:, selector.support_]
y_pred = decisionTree.predict(test_selected)
accuracy_score(y_test_MandY, y_pred)

0.9810126582278481

#### Scoring Methods for KNN

In [261]:
# Perform Univariate Feature Selection
selector = SelectKBest(chi2, k=2)
X_train_MandY_selected = selector.fit_transform(X_train_MandY, y_train_MandY)
X_test_MandY_selected = selector.fit_transform(X_test_MandY, y_test_MandY)

# Tuning k Hyperparameter
max_k = 15
scores = []
for k in range(1, max_k):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_MandY_selected, y_train_MandY)
    y_pred = knn.predict(X_test_MandY_selected)
    cv_results = cross_validate(knn, X_train_MandY_selected, y_train_MandY, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal k: ", scores.index(max(scores))+1)


Best performance:  0.9661971830985914
Ideal k:  12


In [262]:
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train_MandY_selected, y_train_MandY)
y_pred = knn.predict(X_test_MandY_selected)
accuracy_score(y_test_MandY, y_pred)

0.35443037974683544

#### RFE for SVM

In [263]:
estimator = SVC(kernel='linear', C=1)
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_MandY, y_train_MandY)

In [268]:
X_train_MandY_selected = X_train_MandY.loc[:, selector.support_]
X_test_MandY_selected = X_test_MandY.loc[:, selector.support_]

In [269]:
# Tuning C Hyperparameter with selected features
max_C = 15
scores = []
for C in range(1, max_C):
    svm = SVC(kernel='linear', C=C)
    svm.fit(X_train_MandY_selected, y_train_MandY)
    y_pred = svm.predict(X_train_MandY_selected)
    cv_results = cross_validate(svm, X_train_MandY_selected, y_train_MandY, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal C: ", scores.index(max(scores))+1)

Best performance:  0.9873239436619718
Ideal C:  5


In [270]:
svm = SVC(kernel='linear', C=5)
svm.fit(X_train_MandY_selected, y_train_MandY)
y_pred = svm.predict(X_test_MandY_selected)
accuracy_score(y_test_MandY, y_pred)

0.9620253164556962

## Feature selection for E and T

#### RFE for Random Forest

In [271]:
estimator = RandomForestClassifier(max_depth=2, random_state=0)
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_EandT, y_train_EandT)

In [272]:
selector.support_

array([False, False, False, False, False, False,  True, False, False,
       False,  True,  True, False, False,  True, False])

In [273]:
selected = X_train_EandT.loc[:, selector.support_]
selected

y_bar  x2y_br  xy2br  y_ege
5932       7       6      9      5
663        7       5      8      5
6229       6       4      8      5
12824      7       8      9      4
15256     15      10      8      0
...      ...     ...    ...    ...
14244     13       9      4      1
16476      7       6     13      7
10620     12       9      5      2
18848      7       8      8      5
14195     10       9      4      5

[1407 rows x 4 columns]

In [274]:
randomForest = RandomForestClassifier(max_depth=2, random_state=0)
cv_results = cross_validate(randomForest, selected, y_train_EandT, cv=5)
cv_results

{'fit_time': array([0.36182165, 0.43856263, 0.47718239, 0.66194606, 0.28534102]),
 'score_time': array([0.04638338, 0.04900193, 0.09124279, 0.04503107, 0.02953172]),
 'test_score': array([0.92907801, 0.90780142, 0.90747331, 0.95373665, 0.91459075])}

In [194]:
# Tuning max_depth Hyperparameter
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    randomForest = RandomForestClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(randomForest, selected, y_train_EandT, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.9005047828171928
0.9225360288735771
0.9289341510814972
0.9331970419726913
0.9403043840387673
0.9459932863885314
0.9474142500189293
0.9459882385603595
Best performance:  0.9474142500189293
Ideal max depth:  13


In [275]:
randomForest = RandomForestClassifier(max_depth=13, random_state=0)
randomForest.fit(selected, y_train_EandT)
test_selected = X_test_EandT.loc[:, selector.support_]
y_pred = randomForest.predict(test_selected)
accuracy_score(y_test_EandT, y_pred)

0.9299363057324841

#### RFE for Decision Tree

In [276]:
estimator = tree.DecisionTreeClassifier()
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_EandT, y_train_EandT)

In [277]:
selector.support_

array([False, False, False, False, False, False,  True,  True, False,
       False, False,  True,  True, False, False, False])

In [278]:
selected = X_train_EandT.loc[:, selector.support_]
selected

y_bar  x2_bar  xy2br  x_ege
5932       7       5      9      2
663        7       2      8      2
6229       6       2      8      5
12824      7       3      9      2
15256     15       2      8      0
...      ...     ...    ...    ...
14244     13       3      4      1
16476      7       5     13      0
10620     12       3      5      1
18848      7       7      8      3
14195     10       2      4      3

[1407 rows x 4 columns]

In [279]:
decisionTree = tree.DecisionTreeClassifier()
cv_results = cross_validate(decisionTree, selected, y_train_EandT, cv=5, return_train_score=True)
cv_results

{'fit_time': array([0.00899577, 0.00598478, 0.00498748, 0.00806761, 0.00965381]),
 'score_time': array([0.00299263, 0.00299239, 0.00302625, 0.0029974 , 0.00420928]),
 'test_score': array([0.95744681, 0.92907801, 0.96441281, 0.97153025, 0.94661922]),
 'train_score': array([0.97866667, 0.98222222, 0.97424512, 0.97424512, 0.97779751])}

In [202]:
max_depths = [1, 2, 3, 5, 7, 10, 13, 15]
scores = []
for i in range(len(max_depths)):
    decisionTree = tree.DecisionTreeClassifier(max_depth=max_depths[i], random_state=0)
    cv_results = cross_validate(decisionTree, selected, y_train_EandT, cv=5)
    scores.append(np.mean(cv_results.get("test_score")))
    print(np.mean(cv_results.get("test_score")))
print("Best performance: ", max(scores))
print("Ideal max depth: ", max_depths[scores.index(max(scores))])

0.8983720754145528
0.9232452487317332
0.9268039675929431
0.9438656268140633
0.9545291638272634
0.9509679210519675
0.9566618712299034
0.9545266399131774
Best performance:  0.9566618712299034
Ideal max depth:  13


In [280]:
decisionTree = tree.DecisionTreeClassifier(max_depth=13, random_state=0)
decisionTree.fit(selected, y_train_EandT)
test_selected = X_test_EandT.loc[:, selector.support_]
y_pred = decisionTree.predict(test_selected)
accuracy_score(y_test_EandT, y_pred)

0.9426751592356688

#### Scoring Methods for KNN

In [204]:
# Perform Univariate Feature Selection
selector = SelectKBest(chi2, k=2)
X_train_EandT_selected = selector.fit_transform(X_train_EandT, y_train_EandT)
X_test_EandT_selected = selector.fit_transform(X_test_EandT, y_test_EandT)

# Tuning k Hyperparameter
max_k = 15
scores = []
for k in range(1, max_k):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_EandT_selected, y_train_EandT)
    y_pred = knn.predict(X_test_EandT_selected)
    cv_results = cross_validate(knn, X_train_EandT_selected, y_train_EandT, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal k: ", scores.index(max(scores))+1)


Best performance:  0.9054913880445795
Ideal k:  5


In [281]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_EandT_selected, y_train_EandT)
y_pred = knn.predict(X_test_EandT_selected)
accuracy_score(y_test_EandT, y_pred)

0.8089171974522293

#### RFE for SVM

In [283]:
estimator = SVC(kernel='linear', C=1)
selector = RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train_MandY, y_train_MandY)

In [284]:
X_train_MandY_selected = X_train_MandY.loc[:, selector.support_]
X_test_MandY_selected = X_test_MandY.loc[:, selector.support_]

In [285]:
# Tuning C Hyperparameter with selected features
max_C = 15
scores = []
for C in range(1, max_C):
    svm = SVC(kernel='linear', C=C)
    svm.fit(X_train_EandT_selected, y_train_EandT)
    y_pred = svm.predict(X_train_EandT_selected)
    cv_results = cross_validate(svm, X_train_EandT_selected, y_train_EandT, cv=10)
    scores.append(np.mean(cv_results.get("test_score")))

print("Best performance: ", max(scores))
print("Ideal C: ", scores.index(max(scores))+1)

Best performance:  0.8990982776089158
Ideal C:  1


In [287]:
svm = SVC(kernel='linear', C=1)
svm.fit(X_train_EandT_selected, y_train_EandT)
y_pred = svm.predict(X_test_EandT_selected)
accuracy_score(y_test_EandT, y_pred)

0.8535031847133758